openapi: 3.0.1

info:
  title: LAWeb | Service de stratégie
  description: Permet de définir l'ordre dans lequel les exercices sont fait. Peut dépendre du service résultat.
  version: 0.1.0
  license:
    name: MIT License

paths:
  /next:
    post:
      summary: Retourne l'exercice suivant
      tags:
        - Stratégie
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                strategie:
                  type: string
                  enum:
                    - lineaire
                  description: |
                    Nom de la stratégie
                    * `lineaire` - Stragégie lineaire
                exerciceCourant:
                  type: string
                  format: ObjectId
                exercices:
                  type: array
                  items:
                    $ref: './srv-exercice.openapi.yaml#/components/schemas/ExerciceModeleComplet'
      responses:
        '200':
          description: Exercice suivant
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: ObjectId
