openapi: 3.0.1
info:
  title: LAWeb | Service de stratégie
  description: Permet de définir l'ordre dans lequel les exercices sont fait. Peut dépendre du service résultat.
  version: 1.0.0
  license:
    name: MIT License

servers:
  - url: http://127.0.0.1:3002
    description: Serveur local

paths:
  /next:
    post:
      summary: Retourne l'exercice suivant
      tags:
        - Stratégie
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                strategie:
                  type: string
                  enum:
                    - lineaire
                  description: |
                    Nom de la stratégie
                    * `lineaire` - Stragégie lineaire
                exerciceCourant:
                  type: string
                  format: ObjectId
                exercices:
                  type: array
                  items:
                    $ref: './srv-exercice.openapi.yaml#/components/schemas/ExerciceModeleComplet'
      responses:
        '200':
          description: | 
            Renvoie l'exercice suivant, ou un objet vide s'il n'y a plus d'exercice.
          content:
            application/json:
              schema:
                nullable: true
                allOf:
                - type: object
                  properties:
                    id:
                      type: string
                      format: ObjectId
