openapi: 3.0.0
info:
  title: Service de résultat
  description: Il récupère les données utiles pour le professeur
  version: 0.1.0
  license:
    name: MIT License

paths:
  /tentatives:
    post:
      summary: Récupère les tentatives renvoyées par le service évaluation.

      tags:
        - Tentatives
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EvaluationPourResultat'               

      responses:
        '200':
          description: Réponse à la reception des résultats.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string


  /exercices:
    post:
      summary: récupère l'exercice commencé par un étudiant
      tags:
        - Exercices
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExercicePourResultat'
      responses:
        '200':
          description: Réussi


components:
  schemas: 
    ExercicePourResultat:
      type: object
      properties:
        idExo:
          type: string
          format: ObjectId
          description: Id natif de Mongo-db
          example: 507f1f77bcf86cd799439011
        idEtu: 
          type: string
          format: string
          example: 456qsd
        idSession: 
          type: string
          format: string
          example: 45sdf6sdf
        nomExo:
          type: string
          format: string
          example: boucle en C
        nomSession:
          type: string
          format: string
          example: L3 groupe 1 C
        difficulte:
          type: integer
          minimum: 1
          maximum: 10
        themes:
          type: array
          items:
            type: string
            format: keyword
          description: Mots clés/étiquettes de l'exercice
          example:
            - boucle
            - fonction
            - condition
            - trie
        language:
          type: string
          example: C
        session:
          type: string
          example: L3 gp1 2022
        tempsMoyen:
          type: number
          format: float
          description: Le temps moyen estimé pour cette exerice
        tempsMaximal:
          type: number
          format: float
          description: Le temps maximal mis pour cette exercice

    EvaluationPourResultat:
      type: object
      properties:
        idEtu:
          type: string
          format: ObjectId
          description: Id natif de Mongo-db
          example: 45fds4657dsffg56sg5d4cx2
        idExo:
          type: string
          format: ObjectId
          description: Id natif de Mongo-db
          example: 507f1f77bcf86cd799439011
        idSession : 
          type: string
          format: string
          example: 45sdf6sdf
        reponseEtudiant:
          type: string
          description : code écrit par l'étudiant
          example : int a=1; for (int i=0 ; i<n;i++) {a=a*i;}
        logErreurs:
          type: string
          description : message(s) d'erreur(s)
          example : error segmentation ...
        validationExercice:
          type: boolean
          description : vrai si l'exercice et réussi, faux sinon
        dateSoumission :
          type: string 
          format: date-time
          description : date à laquelle le service évaluation à soumis sa réponse