openapi: 3.0.0
info:
  title: Service de résultat
  description: Il récupère les données utiles pour le professeur
  version: 0.1.0
  license:
    name: MIT License

paths:
  /resultats:
    post:
      summary: Récupère les résultats renvoyé par le service évaluation.

      tags:
        - Résultat
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: integer
                exoId:
                  type: integer
                reponseEtudiant:
                  type: string
                log:
                  type: string
                validationExercice:
                  type: boolean
                date:
                  type: object

      responses:
        '200':
          description: Réponse à la reception des résultats.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
