openapi: 3.0.0
info:
  title: Service de résultat
  description: Il récupère les données utiles pour le professeur
  version: 0.1.0
  license:
    name: MIT License

servers:
  - url: http://127.0.0.1:3000
    description: Serveur local

paths:
  /tentatives:
    post:
      summary: Récupère les tentatives renvoyées par le service évaluation.

      tags:
        - Tentatives
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EvaluationPourResultat'

      responses:
        '200':
          description: Réussi
          content:
            application/json:
              schema:
                type: object
                properties:
                  tentative:
                    allOf:
                      - $ref: '#/components/schemas/EvaluationPourResultat'
                      - type: object
                        properties:
                          id: 
                            type: string
                            format: objectId
                            example: 54f6sd5f75df3sdf


  /exercices:
    post:
      summary: récupère la tentative faite par un étudiant
      tags:
        - Exercices
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExercicePourResultat'
      responses:
        '200':
          description: Réussi
          content:
            application/json:
              schema:
                type: object
                properties:
                  exercice:
                    allOf:
                      - $ref: '#/components/schemas/ExercicePourResultat'
                      - type: object
                        properties:
                          estFini: 
                            type: boolean
                            example: false
                          id: 
                            type: string
                            format: objectId
                            example: 623a41aecff8dcfdd896e978
    get:
      summary: Récupère tous les exercices de la base de donées résultat
      tags:
        - Exercices
      responses:
        '200':
          description: Réussi
          content:
            application/json:
              schema:
                type: object
                properties: 
                  exercices:
                    type: array
                    items:
                      allOf:
                        - $ref: '#/components/schemas/ExercicePourResultat'
                        - type: object
                          properties:
                            estFini: 
                              type: boolean
                              example: false
                            id: 
                              type: string
                              format: objectId
                              example: 54f6sd5f75df3sdf



components:
  schemas: 
    ExercicePourResultat:
      type: object
      properties:
        idExo:
          type: string
          format: ObjectId
          description: Id natif de Mongo-db
          example: 507f1f77bcf86cd799439011
        idEtu: 
          type: string
          format: string
          example: 45fds4657dsffg56sg5d4cx2
        idSession: 
          type: string
          format: string
          example: 623a34f35f35bcc5773e0445
        idSeance: 
          type: string
          format: string
          example: 623a34f35f35bcc5773e05e7
        nomExo:
          type: string
          format: string
          example: boucle en C
        nomSession:
          type: string
          format: string
          example: L3 groupe 1 C
        difficulte:
          type: integer
          minimum: 1
          maximum: 10
        themes:
          type: array
          items:
            type: string
            format: keyword
          description: Mots clés/étiquettes de l'exercice
          example:
            - boucle
            - fonction
            - condition
            - trie
        langage:
          type: string
          example: C
        tempsMoyen:
          type: number
          format: float
          description: Le temps moyen estimé pour cette exerice
        tempsMaximum:
          type: number
          format: float
          description: Le temps maximum mis pour cette exercice
        tentatives:
          type: array
          items:
            $ref: '#/components/schemas/Tentative'
          example: []
          description: le code de l'étudiant avec ses logs d'erreur
        debut:
          type: string
          format: date-time
          description: | 
            Date en UTC : heure française - 2H (RFC 3339 sec. 5.6)

            Exemple : 2020-01-01T12:00:00.000Z correspond à 01/01/2020 à 14h00

    EvaluationPourResultat:
      type: object
      properties:
        idExo:
          type: string
          format: ObjectId
          description: Id natif de Mongo-db
          example: 507f1f77bcf86cd799439011
        idEtu:
          type: string
          format: ObjectId
          description: Id natif de Mongo-db
          example: 45fds4657dsffg56sg5d4cx2
        idSession: 
          type: string
          format: string
          example: 623a34f35f35bcc5773e0445
        idSeance:
          type: string
          format: string
          example: 148a34f35f35bcc5773e0745
        reponseEtudiant:
          type: string
          description: code écrit par l'étudiant
          example: int a=1; for (int i=0 ; i<n;i++) {a=a*i;}
        logErreurs:
          type: string
          description: message(s) d'erreur(s)
          example: error segmentation ...
        validationExercice:
          type: boolean
          description: vrai si l'exercice est réussi, faux sinon
          example: false
        dateSoumission:
          type: string 
          format: date-time
          description: |
            Date à laquelle le service évaluation à soumis sa réponse

            Date en UTC : heure française - 2H (RFC 3339 sec. 5.6)

            Exemple : 2020-01-01T12:00:00.000Z correspond à 01/01/2020 à 14h00

    Tentative:
      type: object
      properties:
        idSeance:
          type: string
          format: string
          example: 148a34f35f35bcc5773e0745
        reponseEtudiant:
          type: string
          description : code écrit par l'étudiant
          example: int a=1; for (int i=0 ; i<n;i++) {a=a*i;}
        logErreurs:
          type: string
          description: message(s) d'erreur(s)
          example: error segmentation ...
        validationExercice:
          type: boolean
          description: vrai si l'exercice et réussi, faux sinon
        dateSoumission:
          type: string 
          format: date-time
          description: |
            Date à laquelle le service évaluation à soumis sa réponse

            Date en UTC : heure française - 2H (RFC 3339 sec. 5.6)

            Exemple : 2020-01-01T12:00:00.000Z correspond à 01/01/2020 à 14h00
